// Field definitions tailored for the NPSB network-management interface.
// ISO field numbers map to metadata describing how to (de)serialize values.

const fieldDefinitions = {
  2: {
    label: 'Primary Account Number',
    format: 'llvar',
    lengthRange: { min: 1, max: 19 },
    contentType: 'n',
    encoding: 'bcd',
  },
  3: {
    label: 'Processing Code',
    format: 'fixed',
    length: 6,
    contentType: 'n',
    encoding: 'bcd',
  },
  4: {
    label: 'Amount, Transaction',
    format: 'fixed',
    length: 12,
    contentType: 'n',
    encoding: 'bcd',
  },
  5: {
    label: 'Amount, Settlement',
    format: 'fixed',
    length: 12,
    contentType: 'n',
    encoding: 'bcd',
  },
  6: {
    label: 'Amount, Cardholder Billing',
    format: 'fixed',
    length: 12,
    contentType: 'n',
    encoding: 'bcd',
  },
  7: {
    label: 'Transmission Date & Time',
    length: 10,
    format: 'fixed',
    contentType: 'n',
    encoding: 'bcd',
  },
  10: {
    label: 'Conversion Rate, Cardholder Billing',
    format: 'fixed',
    length: 8,
    contentType: 'n',
    encoding: 'bcd',
  },
  11: {
    label: 'System Trace Audit Number',
    length: 6,
    format: 'fixed',
    contentType: 'n',
    encoding: 'bcd',
  },
  12: {
    label: 'Local Transaction Time',
    length: 6,
    format: 'fixed',
    contentType: 'n',
    encoding: 'bcd',
  },
  13: {
    label: 'Local Transaction Date',
    length: 4,
    format: 'fixed',
    contentType: 'n',
    encoding: 'bcd',
  },
  14: {
    label: 'Expiration Date',
    length: 4,
    format: 'fixed',
    contentType: 'n',
    encoding: 'bcd',
  },
  18: {
    label: 'Merchant\'s Type',
    length: 4,
    format: 'fixed',
    contentType: 'n',
    encoding: 'bcd',
  },
  19: {
    label: 'Acquiring Country Code',
    length: 3,
    format: 'fixed',
    contentType: 'n',
    encoding: 'bcd',
  },
  22: {
    label: 'Point of Service Entry Mode',
    length: 3,
    format: 'fixed',
    contentType: 'n',
    encoding: 'bcd',
  },
  23: {
    label: 'Card Sequence Number',
    length: 3,
    format: 'fixed',
    contentType: 'n',
    encoding: 'bcd',
  },
  25: {
    label: 'POS Condition Code',
    length: 2,
    format: 'fixed',
    contentType: 'n',
    encoding: 'bcd',
  },
  32: {
    label: 'Acquiring Institution ID Code',
    format: 'llvar',
    lengthRange: { min: 1, max: 11 },
    contentType: 'n',
    encoding: 'bcd',
  },
  37: {
    label: 'Retrieval Reference Number',
    length: 12,
    format: 'fixed',
    contentType: 'ans',
    encoding: 'ascii',
  },
  38: {
    label: 'Authorization Code Response',
    length: 6,
    format: 'fixed',
    contentType: 'an',
    encoding: 'ascii',
  },
  39: {
    label: 'Response Code',
    length: 2,
    format: 'fixed',
    contentType: 'an',
    encoding: 'ascii',
  },
  41: {
    label: 'Card Acceptor Terminal Identification',
    length: 8,
    format: 'fixed',
    contentType: 'ans',
    encoding: 'ascii',
  },
  42: {
    label: 'Card Acceptor Identification Code',
    length: 15,
    format: 'fixed',
    contentType: 'ans',
    encoding: 'ascii',
  },
  43: {
    label: 'Card Acceptor Name/Location',
    length: 40,
    format: 'fixed',
    contentType: 'ans',
    encoding: 'ascii',
  },
  47: {
    label: 'Additional Data - National',
    format: 'lllvar',
    lengthRange: { min: 0, max: 999 },
    contentType: 'ans',
    encoding: 'ascii',
  },
  48: {
    label: 'Additional Data - Private',
    format: 'lllvar',
    lengthRange: { min: 0, max: 999 },
    contentType: 'ans',
    encoding: 'ascii',
  },
  49: {
    label: 'Transaction Currency Code',
    length: 3,
    format: 'fixed',
    contentType: 'n',
    encoding: 'bcd',
  },
  50: {
    label: 'Settlement Currency Code',
    length: 3,
    format: 'fixed',
    contentType: 'n',
    encoding: 'bcd',
  },
  51: {
    label: 'Cardholder Billing Currency Code',
    length: 3,
    format: 'fixed',
    contentType: 'n',
    encoding: 'bcd',
  },
  55: {
    label: 'ICC System Related Data',
    format: 'lllvar',
    lengthRange: { min: 0, max: 255 },
    contentType: 'b',
    encoding: 'binary',
  },
  70: {
    label: 'Network Management Information Code',
    length: 3,
    format: 'fixed',
    contentType: 'n',
    encoding: 'bcd',
  },
  103: {
    label: 'Account Identification 2',
    format: 'llvar',
    lengthRange: { min: 0, max: 28 },
    contentType: 'ans',
    encoding: 'ascii',
  },
  112: {
    label: 'Additional Data',
    format: 'lllvar',
    lengthRange: { min: 0, max: 999 },
    contentType: 'ans',
    encoding: 'ascii',
  },
  128: {
    label: 'Message Authentication Code',
    length: 8,
    format: 'fixed',
    contentType: 'an',
    encoding: 'binary',
  },
};

function getFieldDefinition(fieldNumber) {
  return fieldDefinitions[fieldNumber] ?? null;
}

module.exports = {
  getFieldDefinition,
  fieldDefinitions,
};

